[package]
name = "valley_map"
version = "0.0.1"
authors = ["JJJimbo1"]
edition = "2021"

[dependencies]
serde = { version = "1.0.163", optional = true }
fxhash = { version = "0.2.1", optional = true }