[package]
name = "valley_map"
version = "0.0.1"
authors = ["JJJimbo1"]
edition = "2021"

[dependencies]
# serde = { version = "1.0.163", features = ["derive"], optional = true }
serde = { version = "1.0.191", features = ["derive"] }

[lib]
name = "valley_map"
